package tests;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class GroupDeletionTest extends TestBase {

    @Test
    public void testGroupDeletion() throws InterruptedException {
        goToGroupPage();
        selectGroup();
        deleteSelectedGroups();
        returnToGroupForm();
        Thread.sleep(2000);
    }
}
